Document: armybalancer
Title: Debian armybalancer Manual
Author: <insert document author here>
Abstract: This manual describes what armybalancer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/armybalancer/armybalancer.sgml.gz

Format: postscript
Files: /usr/share/doc/armybalancer/armybalancer.ps.gz

Format: text
Files: /usr/share/doc/armybalancer/armybalancer.text.gz

Format: HTML
Index: /usr/share/doc/armybalancer/html/index.html
Files: /usr/share/doc/armybalancer/html/*.html
